#include "nfv_execute.h"
#include <stdio.h>
#include <string.h>

int nfv_executeNode(nfv_resource *o, int level)
{
  if ( o == NULL ) {
    printf("NULL\n");
    return 0;
  }
  if ( strcmp(o->label, "openstack") == 0 ) {
    printf("CONNECTING TO a PoP called %s\n", o->id);
    printf("ATTRIBUTES\n");
    printf("HOST %s %s %s %s\n",
	   nfv_assignment_col_search(o->assignments, "host")->literal_value,
	   nfv_assignment_col_search(o->assignments, "tenant_name")->literal_value,
	   nfv_assignment_col_search(o->assignments, "user")->literal_value,
	   nfv_assignment_col_search(o->assignments, "pass")->literal_value);
    printf("\n");
  }
  if ( strcmp(o->label, "network") == 0 ) {
    printf("CREATING A NETWORK called %s\n", o->id);
    printf("%s\t%s\n",
	   nfv_assignment_col_search(o->assignments, "type")->literal_value,
	   nfv_assignment_col_search(o->assignments, "schema")->literal_value);
    printf("\n");
  }
  if ( strcmp(o->label, "router") == 0 ) {
    printf("CREATING A ROUTER called %s\n", o->id);
    printf("\n");
  }
  if ( strcmp(o->label, "keypair") == 0 ) {
    printf("CREATING A KEYPAIR called %s\n", o->id);
    if ( nfv_assignment_col_search(o->assignments, "nova_generated")->int_value == 1 ) {
      printf("Generated by Nova\n");
    }
    printf("\n");
  }
  if ( strcmp(o->label, "image") == 0 ) {
    printf("CREATING AN IMAGE called %s\n", o->id);
    if ( strcmp(nfv_assignment_col_search(o->assignments, "format")->literal_value, "\"qcow2\"") == 0 ) {
      printf("QCOW2 format from %s\n", nfv_assignment_col_search(o->assignments, "url")->literal_value);
    }
    printf("\n");
  }
  if ( strcmp(o->label, "vdu") == 0 ) {
    printf("CREATING SERVER called %s\n", o->id);
    printf("We are going to need an openstack ...\n");
    printf("Openstack found in symbol table: %s\n",
    	   nfv_symtab_searchByType(o->st, "openstack")->id);
    printf("\n");
  }
  return 0;
}

int nfv_execute(nfv_resource *o, int level)
{
  if (o->child == NULL && o->sibling == NULL) {
    nfv_executeNode(o, level);
  }
  if ( o->child == NULL && o->sibling != NULL ) {
    nfv_executeNode(o, level);
    nfv_execute(o->sibling, level);
  }
  if ( o->child != NULL && o->sibling == NULL ) {
    nfv_executeNode(o, level);
    nfv_execute(o->child, level+1);
  }
  if ( o->child != NULL && o->sibling != NULL ) {
    nfv_executeNode(o, level);
    nfv_execute(o->child, level+1);
    nfv_execute(o->sibling, level);
  }
  return 0;
}

